zones:
  Room_1:
    type: room
    connections:
      - Tube_1
      - Tube_2
      - Tube_3
  Room_2:
    type: room
    connections:
      - Tube_1
      - Tube_3
      - Tube_4
  Room_3:
    type: room
    connections:
      - Tube_2
      - Tube_4