zones:
  Room_1:
    type: room
    connections:
      - Arm_1
      - Arm_2
      - Arm_3
  Room_2:
    type: room
    connections:
      - Arm_1
      - Arm_3
      - Arm_4
  Room_3:
    type: room
    connections:
      - Arm_2
      - Arm_4